name: Build and Deploy to GitHub Pages
on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build site (generate public/)
        env:
          SITE_NAME: ${{ secrets.SITE_NAME }}
          BOOKING_URL: ${{ secrets.BOOKING_URL }}
        run: |
          # defaults used if secrets are not set
          go run ./generate.go --name "${SITE_NAME:-Massage Therapist}" --booking "${BOOKING_URL:-https://your-booking.example}" --out public

      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: public
          token: ${{ secrets.GH_TOKEN }}